apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vegbank.fullname" . }}
  labels:
    {{- include "vegbank.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vegbank.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vegbank.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      volumes:
      - name: {{ .Release.Name }}-db-files-volume
        configMap:
          name: {{ .Release.Name }}-db-files
          defaultMode: 0644
      - name: vegbankdb-init-pgdata
        persistentVolumeClaim:
          claimName: {{ .Values.databaseRestore.pvc }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vegbank.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-init-postgres # Wait for Postgres to start
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup vegbankdb-postgresql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres; sleep 2; done"]
        - name: {{ .Chart.Name }}-setup-postgres # Set-up Postgres if restore is enabled
          # Note: This image should match the postgres version installed
          image: postgres:16
          env:
            - name: VB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: password
            - name: VB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: username
            - name: VB_DB_NAME
              value: {{ .Values.database.name | quote }}
            - name: VB_DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: VB_DB_PORT
              value: {{ .Values.database.port | quote }}
          command:
            - sh
            - -c
            - >
              if [ "{{ .Values.databaseRestore.enabled }}" = "true" ]; then
                echo "## Checking DB env vars";
                env | grep '^VB_DB_' || true;
                echo "## Creating Vegbank database and roles";
                export PGPASSWORD="$POSTGRES_PASSWORD";
                psql \
                -h "$VB_DB_HOST" \
                -p "$VB_DB_PORT" \
                -U "postgres" \
                -d postgres \
                -c "CREATE ROLE vegbank WITH LOGIN PASSWORD '${VB_DB_PASS}';" \
                -c "CREATE DATABASE vegbank WITH ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';" \
                -c "GRANT ALL PRIVILEGES ON DATABASE vegbank TO vegbank;" \
                -c "GRANT USAGE, CREATE ON SCHEMA public TO vegbank;";
              fi
        - name: {{ .Chart.Name }}-init-flyway # Run the flyway database migration
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.flyway.image.repository }}:{{ .Values.flyway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.flyway.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Release.Name }}-db-files-volume
              mountPath: {{ .Values.flyway.dbpath }}/migrations
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: password
            - name: FLYWAY_LOCATIONS
              value: "filesystem:{{ .Values.flyway.dbpath }}/migrations"
          command:
            - sh
            - -c
            - >
              echo "## Flyway Env";
              env | grep '^FLYWAY_' || true;
              echo "## Listing Migrations";
              ls {{ .Values.flyway.dbpath }}/migrations || true;
              if [ "{{ .Values.databaseRestore.enabled }}" = "true" ]; then
                echo "Running partial migrate to {{ .Values.databaseRestore.target }}";
                echo "## Note: If there is no flyway CLI arguments, or conf file, it will default to ENV variables";
                flyway -target={{ .Values.databaseRestore.target }} migrate;
              else
                echo "Running full migration to latest schema in db/migrations";
                flyway migrate;
              fi
        - name: {{ .Chart.Name }}-pg-restore # Restore the database if restore is enabled
          # Note: This image should match the postgres version installed
          image: postgres:16
          volumeMounts:
              # Mount the PVC, it should show the directory that's been mounted on knbvm
            - name: {{ .Values.databaseRestore.pvc }}
              mountPath: "/tmp/databaseRestore"
          env:
            - name: VB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: password
            - name: VB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: username
            - name: VB_DB_NAME
              value: {{ .Values.database.name | quote }}
            - name: VB_DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: VB_DB_PORT
              value: {{ .Values.database.port | quote }}
          command:
            - sh
            - -c
            - >
              if [ "{{ .Values.databaseRestore.enabled }}" = "true" ]; then
                echo "## Checking DB env vars";
                env | grep '^VB_DB_' || true;
                echo "## Database Restore Requested, executing data-only dump file";
                export PGPASSWORD="$VB_DB_PASS";
                psql \
                -h "$VB_DB_HOST" \
                -p "$VB_DB_PORT" \
                -U "$VB_DB_USER" \
                -d "$VB_DB_NAME" \
                -f "{{ .Values.databaseRestore.mountpath }}/{{ .Values.databaseRestore.filepath }}";
              fi
        - name: {{ .Chart.Name }}-apply-flyway # Apply remaining migrations
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.flyway.image.repository }}:{{ .Values.flyway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.flyway.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Release.Name }}-db-files-volume
              mountPath: {{ .Values.flyway.dbpath }}/migrations
          env:
            - name: FLYWAY_URL
              value: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: password
            - name: FLYWAY_LOCATIONS
              value: "filesystem:{{ .Values.flyway.dbpath }}/migrations"
          command:
            - sh
            - -c
            - >
              echo "## Flyway Env";
              env | grep '^FLYWAY_' || true;
              echo "## Listing Migrations";
              ls {{ .Values.flyway.dbpath }}/migrations || true;
              echo "Applying all migrations in db/migrations";
              flyway migrate;
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: VB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: password
            - name: VB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: username
            - name: VB_DB_NAME
              value: {{ .Values.database.name | quote }}
            - name: VB_DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: VB_DB_PORT
              value: {{ .Values.database.port | quote }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
