apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vegbank.fullname" . }}
  labels:
    {{- include "vegbank.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vegbank.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vegbank.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      volumes:
      - name: {{ .Release.Name }}-config-volume
        configMap:
          name: {{ .Release.Name }}-flyway-conf
          defaultMode: 0644
      - name: {{ .Release.Name }}-db-files-volume
        configMap:
          name: {{ .Release.Name }}-db-files
          defaultMode: 0644
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vegbank.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-init-postgres # Wait for Postgres to start
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup vegbankdb-postgresql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres; sleep 2; done"]
        - name: {{ .Chart.Name }}-init-flyway # Run the flyway database migration
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.flyway.image.repository }}:{{ .Values.flyway.image.tag | default .Chart.AppVersion }}"
          # TODO: Determine how this data-only dump file should be handled if partial restore is turned on
          command:
            - sh
            - -c
            - >
              cat {{ .Values.flyway.configpath }} &&
              ls {{ .Values.flyway.dbpath }}/migrations &&
              if [ "{{ .Values.restore.enabled }}" = "true" ]; then
                echo "Running partial migrate to {{ .Values.restore.target }}";
                flyway -password=${VB_DB_PASS} -configFiles={{ .Values.flyway.configpath }} -target={{ .Values.restore.target }} migrate;
              else
                echo "Running full migrate to latest";
                flyway -password=${VB_DB_PASS} -configFiles={{ .Values.flyway.configpath }} migrate;
              fi
          imagePullPolicy: {{ .Values.flyway.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Release.Name }}-config-volume
              mountPath: {{ .Values.flyway.configpath }}
              subPath: flyway.conf
            - name: {{ .Release.Name }}-db-files-volume
              mountPath: {{ .Values.flyway.dbpath }}/migrations
          env:
            - name: VB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: password
            - name: VB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: username
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: VB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: password
            - name: VB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: vegbankdbcreds
                  key: username
            - name: VB_DB_NAME
              value: {{ .Values.database.name | quote }}
            - name: VB_DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: VB_DB_PORT
              value: {{ .Values.database.port | quote }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
