# Custom CNPG Resource for Scheduled Backups
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vegbankdb-scheduled-backup
spec:
  cluster:
    name: vegbankdb-cnpg # Name of the CNPG Cluster - you can confrim this by executing `kubectl get cluster -n vegbank-dev`
  method: volumeSnapshot
  backupOwnerReference: self
  schedule: '0 0 21 * * *' # At 9pm every day
  immediate: true