######################################################################################
#     D O   N O T   C H E C K   C R E D E N T I A L S   I N T O   G I T H U B ! ! !
######################################################################################
#
apiVersion: v1
kind: Secret
metadata:
  name: vegbankdbcreds 
type: kubernetes.io/basic-auth 
## @param stringData write-only, non-binary secret data (eg credentials) in string form.
##
## # # #    NEVER CHECK SECRETS INTO GITHUB!   # # #
##
stringData:
  ## @param 'username'
  ## The username for the vegbank postgres user. This is in the secret for later use by CNPG even though it doesn't necessarily need to be secret. 
  username: vegbank
  ## @param 'password'
  ## the Postgres database password for the vegbank user
  ##
  ## IMPORTANT NOTE: Once the chart is deployed, it is not possible to change the application's
  ## access credentials, such as usernames or passwords, using Helm. To change these application
  ## credentials after deployment, delete any persistent volumes (PVs) used by the chart and
  ## re-deploy it, or use the application's built-in administrative tools if available.
  ##
  password: "YOUR-PASSWORD-HERE"
